-- vim.cmd('hi Cursor cterm=NONE gui=reverse ctermfg=black guifg=black ctermbg=white guibg=white')
-- vim.cmd('hi TermCursor cterm=NONE gui=reverse ctermfg=black guifg=black ctermbg=white guibg=white')
-- vim.cmd('hi CursorLine cterm=NONE gui=NONE ctermfg=NONE guifg=NONE ctermbg=235 guibg=#202020')
vim.cmd('hi Search cterm=reverse gui=reverse ctermfg=cyan guifg=cyan ctermbg=black guibg=black')
vim.cmd('hi IncSearch cterm=reverse gui=reverse ctermfg=cyan guifg=cyan ctermbg=black guibg=black')
vim.cmd('hi CurSearch cterm=NONE gui=NONE ctermfg=cyan guifg=cyan ctermbg=black guibg=black')
-- vim.cmd('hi Comment ctermfg=Grey ctermbg=NONE guifg=Grey guibg=NONE')
-- vim.cmd('hi Folded ctermfg=red ctermbg=NONE guifg=red guibg=NONE')
-- vim.cmd('hi ColorColumn ctermbg=darkgrey guibg=#101010')
-- vim.cmd('hi LineNr ctermfg=red ctermbg=0 guifg=#303030 guibg=black')
-- vim.cmd('hi SpellCap ctermbg=81 ctermfg=black')
-- vim.cmd('hi MatchParen cterm=NONE ctermfg=yellow ctermbg=black')
-- vim.cmd('hi DiffDelete ctermfg=0 ctermbg=241')
-- vim.cmd('hi DiffAdd ctermfg=blue ctermbg=white')
-- vim.cmd('hi MiniTablineCurrent gui=NONE guifg=#000000 guibg=#666666')
-- vim.cmd('hi MiniTablineVisible gui=NONE guifg=#888888 guibg=#222222')
-- vim.cmd('hi MiniTablineHidden gui=NONE guifg=#444444 guibg=#222222')
-- vim.cmd('hi MiniTablineModifiedCurrent gui=NONE guifg=#000000 guibg=#888800')
-- vim.cmd('hi MiniTablineModifiedVisible gui=NONE guifg=#888800 guibg=#222222')
-- vim.cmd('hi MiniTablineModifiedHidden gui=NONE guifg=#666600 guibg=#222222')
-- vim.cmd('hi MiniTablineTabpagesection gui=NONE guifg=#888888 guibg=#222222')
-- vim.cmd('hi MiniTablineFill gui=NONE guifg=#666666 guibg=#222222')
-- vim.cmd('hi MiniTablineTrunc gui=NONE guifg=red guibg=green')
-- vim.cmd('syn match ErrorMsg /\\s\\+$/')
