vim.cmd('colorscheme vividchalk')

vim.cmd('hi Cursor cterm=NONE gui=reverse ctermfg=black guifg=black ctermbg=white guibg=white')
vim.cmd('hi TermCursor cterm=NONE gui=reverse ctermfg=black guifg=black ctermbg=white guibg=white')
vim.cmd('hi CursorLine cterm=NONE gui=NONE ctermfg=NONE guifg=NONE ctermbg=235 guibg=#202020')
vim.cmd('hi Search cterm=reverse gui=reverse ctermfg=cyan guifg=cyan ctermbg=black guibg=black')
vim.cmd('hi IncSearch cterm=reverse gui=reverse ctermfg=cyan guifg=cyan ctermbg=black guibg=black')
vim.cmd('hi CurSearch cterm=NONE gui=NONE ctermfg=cyan guifg=cyan ctermbg=black guibg=black')
vim.cmd('hi Comment ctermfg=Grey ctermbg=NONE guifg=Grey guibg=NONE')
vim.cmd('hi Folded ctermfg=red ctermbg=NONE guifg=red guibg=NONE')
vim.cmd('hi ColorColumn ctermbg=darkgrey guibg=#101010')
vim.cmd('hi LineNr ctermfg=red ctermbg=0 guifg=#303030 guibg=black')
vim.cmd('hi SpellCap ctermbg=81 ctermfg=black')
vim.cmd('hi MatchParen cterm=NONE ctermfg=yellow ctermbg=black')
vim.cmd('hi DiffDelete ctermfg=0 ctermbg=241')
vim.cmd('hi DiffAdd ctermfg=blue ctermbg=white')
